ja.common.docker_context.IDockerContext *-- "*" ja.common.docker_context.MountPoint
ja.common.job.JobStatus "1" --* ja.common.job.Job
ja.common.job.JobPriority "1" --* ja.common.job.JobSchedulingConstraints

ja.common.job.JobSchedulingConstraints "1" --* ja.common.job.Job

ja.common.job.Job *-- "1" ja.common.docker_context.IDockerContext
ja.common.job.Job *-- "1" ja.common.docker_context.DockerConstraints

ja.common.proxy.proxy.Proxy *-- "1" ja.common.proxy.ssh.SSHConnection
ja.common.proxy.proxy.Proxy "1" -- "1" ja.common.proxy.remote.Remote
ja.common.proxy.remote.Remote "0..*" -- "1" ja.common.proxy.command_handler.CommandHandler
ja.common.proxy.ssh.SSHConnection "0..*" o-- "1" ja.common.proxy.ssh.SSHConfig
ja.common.message.base.Command "0..*" -- ja.common.proxy.command_handler.CommandHandler
ja.common.message.base.Response "0..*" -- ja.common.proxy.command_handler.CommandHandler

ja.user.config.base.UserConfig *-- "1" ja.common.proxy.ssh.SSHConfig
ja.user.config.base.UserConfig *-- "1" ja.user.config.base.Verbosity
ja.worker.config.WorkerConfig  *-- "1" ja.common.proxy.ssh.SSHConfig
ja.worker.config.WorkerConfig *-- "1" ja.common.work_machine.ResourceAllocation
ja.user.config.add.AddCommandConfig "1" *-- "1" ja.common.job.Job
